### PR TITLE
Fix CheckBoxDemo.qml canno be loaded

### PR DESCRIPTION
**Pull request by rossHell**
"Checkbox" is wrong in components array. It should be "CheckBox" to be able to load the qml file CheckBoxDemo.qml. 
Otherwise the error "file:///.../qml-material/modules/Material/Checkbox.qml: File name case mismatch" is encountered.

### CODE REVIEW

**Comment by boghison** [comment]
Why did you close this PR?

**Comment by jneidlinger** [comment]
It actually is supposed to be Checkbox. When the Checkbox merge was pulled in, CheckBox had been renamed to Checkbox (the correct casing), but git ignored the renames. @iBeliever is aware of the issue, I just don't think he has manually ran "git mv -r CheckBox.qml Checkbox.qml" yet

**Comment by rossHell** [comment]
It was an error something is wrong but not this

**Comment by jneidlinger** [comment]
"git mv -r CheckBox.qml Checkbox.qml" and "git mv -r CheckBoxDemo.qml CheckboxDemo.qml" 
need to be ran directly by someone with push rights on this repo.

**Comment by boghison** [comment]
@rossHell What do you mean by that?
@jneidlinger I'll do it then

**Comment by boghison** [comment]
@jneidlinger That first move, it's for the modules/Material directory, right? But won't that break other things that are using the CheckBox?

**Comment by iBeliever** [comment]
I'm closing now as the component should correctly be named "Checkbox", and @boghison pushed that fix to develop.

**Comment by iBeliever** [comment]
Oh, never mind, it was closed a while ago :)

**Pull request closed without merging**
