### PR TITLE
(Fix & Improvement) ToolBar -  implicit width and tabbar position

### PR DESCRIPTION
**Pull request by AnonymHax**
- Fix the undefined implicitWidth (needed in case of scroll area)

- Added possibility to center the tabbar - (bool tabbarCentered) -
which is crucial to respect the norms of Material

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsOGUyd0ZGSWhwdkE/components_tabs_usage_desktop7.png

### CODE REVIEW

**Comment by iBeliever** [comment]
Tab centering is supported as of https://github.com/papyros/qml-material/commit/be055438ec434cf4ebcd422d6f967675ccc0e3e2. Could you explain what you mean by the `implicitWidth` being necessary for a scroll area?

**Comment by AnonymHax** [comment]
It is needed to give to a Flickable the value of contentWidth opposed to its width

**Comment by iBeliever** [comment]
@AnonymHax Right, but why would you put a Toolbar in a Flickable? The toolbar isn't supposed to be scrollable - anything scrollable should be inside the toolbar, vs the toolbar itself.

**Comment by AnonymHax** [comment]
Yeah well I just missed this - but it seems the tabbar should be scrollable
when there is not enough place and that you don't to implement a
NavigationDrawer
Le 17 sept. 2015 02:44, "Michael Spencer" <notifications@github.com> a
écrit :

**Comment by iBeliever** [comment]
@AnonymHax Ah, I see, you want to be able to scroll the tabs when there are too many too fit within the available width. In that case, only the tabs should scroll, not the entire toolbar. I have a separate issue open to track work on scrollable tabs: #282.

**Comment by AnonymHax** [comment]
Yes thats exactly it - I just have an empty toolbar that's why I didn't see
the problem - I am going to work on that ! Btw this api is great ! I am
converting my app to it, I'd be glad to help
Le 17 sept. 2015 02:50, "Michael Spencer" <notifications@github.com> a
écrit :

**Comment by iBeliever** [comment]
Cool, thanks @AnonymHax. I'm going to close this pull request, and if you do implement scrollable tabs, you're welcome to open a new pull request for that.

**Pull request closed without merging**
