### PR TITLE
[TextField] Port to QtQuick.Controls [WIP]

### PR DESCRIPTION
**Pull request by ricardomv**
Having some issues with `placeholderTextComponent`. Maybe we will need to send a patch to QtQuickControls moving the text into the style so we can change it's position.

### CODE REVIEW

**Comment by iBeliever** [comment]
@ricardomv Are you ready for me to review this or did you plan to do more work (based on the WIP in the title)?

**Comment by ricardomv** [comment]
I have an issue with `placeholderText` from QtControls i need a way to chage it to make the floating placeholder

**Comment by jneidlinger** [comment]
@ricardomv FYI we used to have TextField working based on QtQuick.Controls, but was changed for whatever reason in favor of basing it on a standard text input.

See here: https://github.com/papyros/qml-material/blob/7212043be781597f854f0320721463ea7aefe381/modules/Material/TextField.qml

**Comment by ricardomv** [comment]
the solution there was to set `placeholderTextColor` to transparent, wich we can do but i would like to use the text component aleady in Controls.

**Comment by jneidlinger** [comment]
Agreed, but it make some time to wait on an upstream change from QT for a non-bug feature request...

**Comment by ricardomv** [comment]
has some ugly hacks but should work as expected

**Comment by iBeliever** [comment]
@ricardomv Looking nice, I tested it and it works great! Would you mind splitting the style into a separate file like I've done with several of the components, so we can theme the regular QtQuick.Controls TextField and then add the extra MD properties and force the style through our subclass?

**Comment by iBeliever** [comment]
Great work on this, thanks!

**Pull request closed without merging**
