### PR TITLE
Add RobotoMono font to the project

### PR DESCRIPTION
**Pull request by glaucopgomes**
In a personal project I needed a monospaced font, and RobotoMono was the logical choice. Now, I want to contribute this back.

### CODE REVIEW

**Comment by VirusKA** [comment]
this is necessary for the terminal as well

**Comment by ricardomv** [comment]
I think we should create a separate repository just for fonts or make them a dependencie.

**Comment by VirusKA** [comment]
@ricardomv I like that idea alot!

**Comment by iBeliever** [comment]
For many projects, there's no need to use the Mono font, unlike the regular Roboto fonts, which are required for Material Design. Because of that, I think it's better for developers to just include fonts on their own (or have them installed globally as part of a Linux package dependency).

**Pull request closed without merging**
