### PR TITLE
Improve Dialog by adding open(), close() and accepted/rejected signals. Also fix height of the dialog.

### PR DESCRIPTION
**Pull request by EgorMatirov**
Now it's more similar to [QML Dialog] (http://doc.qt.io/qt-5/qml-qtquick-dialogs-dialog.html) which makes porting to\from QtQuick.Dialogs a bit more easier.

### CODE REVIEW

**Comment by boghison** [comment]
@EgorMatirov Please add my copyright as well (I forgot to add it when I was improving the dialog, *substantially*, you can find it in the `Wave.qml` file).

**Comment by EgorMatirov** [comment]
That fixes wrong height of dialog. For example, I have set contents to Text item.
Before it was (flickable is interactive):
before1
before2
After:
after

**Comment by boghison** [comment]
Looks cool

**Comment by iBeliever** [comment]
Great work, thanks for the improvements.

**Pull request merged**
