### PR TITLE
[Slider] Add customization options to the slider's floating knob

### PR DESCRIPTION
**Pull request by jneidlinger**
This allows the knob's floating label to have its value customized.
The label will adjust its size and positioning to best fit the knobs size, which is also now configurable.

Example:

customizedslider

### CODE REVIEW

**Comment by ricardomv** [comment]
This is not in the spec so i think we shouldn't add it. Why do you need the percent next to the number? I don't like the text scaling it looks too big in only one number and too small with 3.

**Comment by jneidlinger** [comment]
It is a customization option, not a default. Default is to just show the raw slider's value.

The spec says nothing about what the value label should show, in other words, its left up to developer to chose what to show in the slider. This simply provides the ability to do just that.

**Comment by VirusKA** [comment]
I believe @jneidlinger is right. it's left to the developer to decide.

**Comment by iBeliever** [comment]
Thanks for the pull request!

**Pull request closed without merging**
