### PR TITLE
[WIP] Refactoring and improvements

### LINKED ISSUE #358: Create a qpm package
http://www.qpm.io

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29772844-create-a-qpm-package?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #359: Create a C++ plugin module
I've wanted to avoid doing this to keep the library as simple as possible, but I think we'll have some significant improvements from doing so.

* Calculate dp correctly and on a per-screen basis (#230)
* Possibly add image providers (#336)
* Handle anything else that should best be done in C++ (for performance reasons, etc) (#337)

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29773127-create-a-c-plugin-module?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #363: Clean up the module structure
@marco-piccolino was suggesting in #328 that we should restructure the library into multiple submodules for core components, additional components, etc.

Here's one possible module structure that splits components into several well-defined modules (I'd have to go though each component and make sure they're in the right modules based on their dependencies, but this would be a rough draft):

    Material
    ├── Components                              // Material Design components not in QtQuick.Controls
    │   ├── ActionButton.qml
    │   ├── Card.qml
    │   ├── DatePicker.qml
    │   ├── IconButton.qml
    │   ├── MenuField.qml
    │   ├── ProgressCircle.qml
    │   ├── Scrollbar.qml
    │   ├── Sidebar.qml
    │   ├── Snackbar.qml
    │   ├── ThinDivider.qml
    │   ├── TimePicker.qml
    │   ├── Tooltip.qml
    │   └── Wave.qml
    ├── Controls                                // Materialized version of QtQuick.Controls
    │   ├── Action.qml
    │   ├── Button.qml
    │   ├── CheckBox.qml
    │   ├── Label.qml
    │   ├── ProgressBar.qml
    │   ├── RadioButton.qml
    │   ├── Slider.qml
    │   ├── Switch.qml
    │   ├── Tab.qml
    │   └── TextField.qml
    ├── Core                                    // Core Material stuff
    │   ├── AwesomeIcon.qml
    │   ├── Device.qml
    │   ├── Icon.qml
    │   ├── Ink.qml
    │   ├── MaterialAnimation.qml
    │   ├── Object.qml
    │   ├── Palette.qml
    │   ├── PlatformExtensions.qml
    │   ├── Theme.qml
    │   ├── ThemePalette.qml
    │   ├── Units.qml
    │   └── View.qml
    ├── Extras                                  // Extra stuff that nothing else depends on
    │   ├── AutomaticGrid.qml
    │   ├── CMakeLists.txt
    │   ├── CircleImage.qml
    │   ├── CircleMask.qml
    │   ├── ColumnFlow.qml
    │   ├── Image.qml
    │   ├── images
    │   │   └── circle.png
    │   ├── js
    │   │   ├── dateutils.js
    │   │   ├── httplib.js
    │   │   ├── listutils.js
    │   │   ├── promises.js
    │   │   └── utils.js
    │   └── qmldir
    ├── ListItems                               // List items
    │   ├── BaseListItem.qml
    │   ├── CMakeLists.txt
    │   ├── Divider.qml
    │   ├── SectionHeader.qml
    │   ├── SimpleMenu.qml
    │   ├── Standard.qml
    │   ├── Subheader.qml
    │   ├── Subtitled.qml
    │   └── qmldir
    ├── Popups                                  // Popups, dialogs, popovers, etc
    │   ├── BottomActionSheet.qml
    │   ├── BottomSheet.qml
    │   ├── Dialog.qml
    │   ├── Dropdown.qml
    │   ├── InputDialog.qml
    │   ├── OverlayView.qml
    │   ├── Popover.qml
    │   ├── PopupBase.qml
    │   └── TimePickerDialog.qml
    └── Window                                  // Stuff that requires a custom root component to work
        ├── ActionBar.qml
        ├── AppTheme.qml
        ├── ApplicationWindow.qml
        ├── MainView.qml
        ├── NavigationDrawer.qml
        ├── OverlayLayer.qml
        ├── Page.qml
        ├── PageSidebar.qml
        ├── PageStack.qml
        ├── TabBar.qml
        ├── TabbedPage.qml
        ├── Toolbar.qml
        └── Window.qml

@marco-piccolino @ricardomv @geiseri @jneidlinger @oKcerG what do you guys think of this module layout? Are there too many modules, or this a good amount with good criteria for separation?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29790426-clean-up-the-module-structure?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #380: Take advantage of the new HiDPI support coming in Qt 5.6
https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30313832-take-advantage-of-the-new-hidpi-support-coming-in-qt-5-6?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #381: Missing my_library_music.svg
I get:
`file:///usr/lib64/qt5/qml/Material/Icon.qml:63:5: QML Image: Cannot open: file:///usr/lib64/qt5/qml/Material/icons/av/my_library_music.svg`
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30398097-missing-my_library_music-svg?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #382: CMake Warning: Policy CMP0063 is not set: Honor visibility properties for all target types
Builds and appears to install properly but haven't done any testing to ensure.

```
07:21 $ uname -r
4.3.3-3-ARCH

07:21 $ cmake --version
cmake version 3.4.3

07:22 $ pacman -Q extra-cmake-modules
extra-cmake-modules 5.18.0-1

07:22 $ git log
commit 2984904b9777625a5bf897e87773814f52525a4a
```

I get the following during cmake:

```
✔ ~/Build/qml-material/build [develop|✔]
07:15 $ cmake ../
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- 
-- The following REQUIRED packages have been found:

 * ECM (required version >= 0.0.11)
 * Qt5Core
 * Qt5Network (required version >= 5.5.1)
 * Qt5Qml
 * Qt5Gui (required version >= 5.5.1)
 * Qt5Quick
 * Qt5Test
 * Qt5Widgets (required version >= 5.5.1)
 * Qt5QuickTest
 * Qt5 (required version >= 5.4.0)

-- Configuring done
CMake Warning (dev) at tests/CMakeLists.txt:9 (add_executable):
  Policy CMP0063 is not set: Honor visibility properties for all target
  types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "materialtests" of type "EXECUTABLE" has the following visibility
  properties set for CXX:

    CXX_VISIBILITY_PRESET
    VISIBILITY_INLINES_HIDDEN

  For compatibility CMake is not honoring them for this target.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/dan/Build/qml-material/build
```
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30408274-cmake-warning-policy-cmp0063-is-not-set-honor-visibility-properties-for-all-target-types?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #384: Remove hard dependency on ECM (KDE Frameworks)
Right now it is not clear why ECM is needed for cmake.  This causes issues for embedded installations that do not require KDE to run Qt only applications.  Is KDE frameworks going to become a hard dependency in the future?
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30505533-remove-hard-dependency-on-ecm-kde-frameworks?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #394: build error ubuntu 15.10
I've built qt from git. I can not build qml-material with qt 5.5.0, qt 5.6.0, qt 5.6.1, qt 5.7.0 getting various errors like this(for 5.6.0):

> CMake Error at CMakeLists.txt:33 (find_package):
>   Could not find a package configuration file provided by "Qt5" (requested
>   version 5.4.0) with any of the following names:
> 
> ```
> Qt5Config.cmake
> qt5-config.cmake
> ```
> 
>   Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
>   to a directory containing one of the above files.  If "Qt5" provides a
>   separate development package or SDK, be sure it has been installed.
> 
> -- Configuring incomplete, errors occurred!
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/32083392-build-error-ubuntu-15-10?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F7838182&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by iBelieve**
- Initial work on a QPM package
- Add a C++ plugin
- Implement Device and Units in C++
- Units uses the new HiDPI code from Qt 5.6, defaulting to new per-screen calculations on Qt 5.5 and earlier.
- Units.dp/Units.gu become properties instead of functions because C++ methods won't trigger binding updates like properties do
- Units.dp/Units.gu are exposed as dp/gu in all the top-level Window via UnitsHelper
- Icons/fonts are no longer all included. Icons are only included as necessary via the icons.yml file and icons.py script

TODO:
- [x] Implement optional fonts
- [x] Verify that the QPM package will work
- [x] Fix failing unit tests

Fixes #384 
Fixes #382 
Fixes #380 
Fixes #363 
Fixes #359 
Fixes #358
Fixes #394 
Fixes #381

### CODE REVIEW

**Comment by marco-piccolino** [comment]
this is huge! looking forward to the merge

**Comment by IdrissDimson** [comment]
This seems like a really exciting update!

**Comment by nimaim** [comment]
Agree, this seems like one hell of an update! Thanks @iBeliever !

**Comment by alexkreidler** [comment]
Yay! It is merged!

**Comment by IdrissDimson** [comment]
\o/ Now to work on 0.2!

**Comment by luntik2012** [comment]
Thank you!
I don't know, where could I ask this, but what you guys think about QtLabControls? Will you merge with it? Did you seen it? Will you assist Qt-team with this somehow?

**Pull request merged**
