### PR TITLE
Update travis qt 5.6.1

### PR DESCRIPTION
**Pull request by Issam-Wakidi**
travis check failled, reason : 
The command "sudo add-apt-repository -y ppa:beineri/opt-qt56-trusty" failed and exited with 1 during .
Fix : 
replacing it with the latest version [ppa:beineri/opt-qt561-trusty](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt561-trusty)

### CODE REVIEW

**Comment by Issam-Wakidi** [comment]
fix #456

**Comment by Issam-Wakidi** [comment]
so now it's failling because of a missing icon icons/navigation_menu.svg, and this will be fixed in another branch/pull request

**Comment by Issam-Wakidi** [comment]
if #459 and #454 get merged as well the travis fail will disapear.

**Comment by iBelieve** [comment]
Thanks for the pull request! :+1:

**Pull request closed without merging**
