### PR TITLE
Material icons: update to 2.2.0

### PR DESCRIPTION
**Pull request by marco-piccolino**
I also reordered the folders in the script alphabetically as one folder ("places") was missing.
@geiseri should we remove the main.sh script which is contained in the icons folder? /scripts/make_icons.sh is up to date.
@iBeliever if this looks ok, would you mind pulling at your earliest convenience? thanks

### CODE REVIEW

**Comment by marco-piccolino** [comment]
@nbigaouette I tried running the resources script but on OSX I get a double slash on paths:

Some examples:

<file>Material/icons//action/assignment.svg</file>

<file>Material//fonts/fontawesome/FontAwesome.otf</file>

<file>Material/fonts/roboto//Roboto-Black.ttf</file>

<file>Material//Action.qml</file>

<file>QtQuick//Controls/Styles/Material/ApplicationWindowStyle.qml</file>

Would you mind taking a look? thanks!

**Comment by nbigaouette** [comment]
@marco-piccolino You are right, an extra slash is appended. It shouldn't matter much though as it is ignored. To fix, remove the trailing slashes in the _Folder to search_ column of the different `generate_resource_file` calls.

For example, change:

``` bash
generate_resource_file 'FontRoboto.qrc'         'Material/fonts/roboto/'  '*.ttf'
```

to

``` bash
generate_resource_file 'FontRoboto.qrc'         'Material/fonts/roboto'  '*.ttf'
```

Tested on Linux and OSX.

**Comment by marco-piccolino** [comment]
@nbigaouette awesome, thanks. please see https://github.com/papyros/qml-material/commit/4af0e33123f3b9cdf251c720d411d961fdb9e1c6#commitcomment-16122398

**Comment by geiseri** [comment]
@marco-piccolino yes, you can remove that main.sh script if everything is up to date.

**Comment by nbigaouette** [comment]
@marco-piccolino see #392

**Comment by marco-piccolino** [comment]
@nbigaouette thank you!
@iBeliever looks like this is ready for being pulled!

**Comment by iBelieve** [comment]
Thanks for the pull request! In my recent refactoring, I've ditched shipping all the icons with qml-material. Instead, just add the icons you want to an `icons.yml` file, run the `icons.py` script in the `scripts` folder, and include the resulting `icons/icons.qrc` file in your project. To update icons, just delete the `icons` folder and re-run the script.

**Comment by marco-piccolino** [comment]
Sounds good!
Il 02 apr 2016 9:16 PM, "Michael Spencer" notifications@github.com ha
scritto:

**Pull request closed without merging**
