### PR TITLE
Update the font awesome script

### PR DESCRIPTION
**Pull request by geiseri**
Addresses #165

### CODE REVIEW

**Comment by geiseri** [comment]
Is this a false positive?  It seems valid and operates correctly in the view.
```
modules/Material/awesome.js
 #1 Unexpected '\'.
    'space' : '\u0020', // Line 35, Pos 17
```

**Comment by iBeliever** [comment]
Thanks for the pull request! I'm not sure why that is failing, it does seem like a false positive. I'm going to post a question to the [JSLint G+ community](https://plus.google.com/communities/104441363299760713736) and hopefully get an answer on that.

Anyhow, this script doesn't correctly work, as it's missing many of the icons (compare the line length before with line length after running the script). There are also weirdly named icons like `uniF1D1`, which certainly isn't on the FontAwesome cheatsheet. That's the reason why I was planning to use a python script to pull down the cheatsheet and parse the icons from. That way we know it works 100%.

**Comment by geiseri** [comment]
That is strange. I know it pulls from the glyph tables, so it will show
ones that are auxiliary for Unicode. Let me check if there is a table
missing. I still think parsing the font raw would be best since it could be
made generic to any glyph fonts.

**Comment by geiseri** [comment]
@iBeliever is this more in line with your vision?  It does look like the python name was failing to parse some of the names.  So in the end it looks like it will be easier to use your method of just pulling the files.  I also combined the pulling of the otf file in the same step so that everything stays in sync.

**Comment by iBeliever** [comment]
Great work on this, thank you! I merged in your script with some changes to get it to work on Python 3, since that's the default python version on Arch.

**Pull request closed without merging**
