### PR TITLE
[Feature] ProgressCircle - Adds the material design circular progress indicator

### PR DESCRIPTION
**Pull request by jneidlinger**
Adds the material design circular progress indicator as seen here:
http://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators

(Low FPS) in action:
progresscircle

Let me know what you guys think!

### CODE REVIEW

**Comment by ricardomv** [comment]
Maybe drop the color cycling functionality as it can be done outside the core implementation and as it is now the colors can't be customized. moving it to the demo would be fine.
That being said the implementation itself looks good.

**Comment by jneidlinger** [comment]
Added determinate progress ability. This follows googles example as well.

determinateprogress

**Comment by jneidlinger** [comment]
Tweaked the indeterminate animation quite a bit. Very close to google's now.
determinateprogresstweak

**Comment by jneidlinger** [comment]
Updated this to be based on QtQuick controls ProgressBar, and squashed everything down.

**Comment by ricardomv** [comment]
If you could center the circles in the demo (just add `Layout.alignment: Qt.AlignCenter`) it would be perfect :smiley: . Apart from that LGTM :+1: Nice work.

**Comment by jneidlinger** [comment]
@ricardomv done :)

**Comment by iBeliever** [comment]
Thanks for your great work on this!

**Pull request closed without merging**
