### PR TITLE
[Dialog] Expose dialog buttons via aliases

### PR DESCRIPTION
**Pull request by jneidlinger**
Simply exposes the underlying negative and positive buttons through aliases so that their properties can be customized as needed by those using dialogs

### CODE REVIEW

**Comment by ricardomv** [comment]
Wouldn't this work better with actions and add a warning if more than 3 buttons are added

**Comment by jneidlinger** [comment]
The material design spec pretty clearly shows the only actions that are deemed acceptable are buttons.... and if any of them shown, it should always be two. If two buttons are shown, the dismissive button is always to the left of the affirmative button. Therefore, the predefined structure we have should be sufficient, with these aliases providing an advanced option to be able to tweak the buttons properties.

http://www.google.com/design/spec/components/dialogs.html#dialogs-confirmation-dialogs

**Comment by ricardomv** [comment]
@jneidlinger i just wanted to merge the signals, text and the component in one place. `negativeButtonText` for example can be set in `negativeButton.text` can you remove those properties?

**Comment by ricardomv** [comment]
btw what properties do you need to change in the buttons?

**Comment by glaucopgomes** [comment]
I do not know if it's the same case of @jneidlinger, but in my actual use case I need to set the visibility of only one of the buttons.

**Comment by iBeliever** [comment]
Thanks for the improvement!

**Pull request closed without merging**
