### PR TITLE
[Dialog] Update dialog spec / behavior to match latest MD spec

### PR DESCRIPTION
**Pull request by jneidlinger**
Demo:

dialogupdate

Matches these MD spec examples:

image

image

image

### CODE REVIEW

**Comment by ricardomv** [comment]
@jneidlinger can you rebase this on develop, looks like you're 10 commits behind

**Comment by jneidlinger** [comment]
Should be up to date now

**Comment by ricardomv** [comment]
Please use `git rebase -i HEAD^` and fix merge issues in `Dialog.qml` Than push changes with `git push origin bug/dialog_layout --force`

**Comment by jneidlinger** [comment]
Picky picky. Okay, done.

**Comment by jneidlinger** [comment]
Fixes #223

**Comment by VirusKA** [comment]
^ can anyone confirm this?

**Comment by iBeliever** [comment]
Nice improvements, thank you!

**Pull request closed without merging**
