### PR TITLE
Fix Snackbar button margins, color and a little more

### PR DESCRIPTION
**Pull request by cyberbobs**
The result seems a little bit closer to [Material Design spec](http://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-specs) and looks nicer IMO

Before:
image

After:
image

### CODE REVIEW

**Comment by jneidlinger** [comment]
Good work. One thing I see is that it looks like we aren't conforming to the minimum width specified in the Material design guidelines:

(Tablet / Desktop)
Minimum width: 288dp

Can you fix that too?

**Comment by cyberbobs** [comment]
Done :)

Also added a small fix preventing newly opened toast to close immediately if the previous toast was still shown at the moment of opening the new one.

**Comment by jneidlinger** [comment]
Nice! Yeah I noticed that issue with previous toast timers killing the new one, good fix.

**Comment by ricardomv** [comment]
@cyberbobs Shouldn't the ripples in the button go to the edge of the snackbar? It looks a bit odd right now.

**Comment by cyberbobs** [comment]
@ricardomv I currently have no Lollipop devices around, but as far as I remember there is no ripple at all, just a little text brightness alteration.

Using full ripple will probably also be not the best way since not the whole toast area is touch active, only a small part of it is. 

BTW, there is currently no way of disabling ripple in Ink element since it is based on MouseArea item instead of attaching to one, so there is several ways of fixing this one:
* Adding ability to disable ripple effect to Ink item
* Adding ability to disable ripple effect to Button item by replacing Ink item with plain MouseArea
* Splitting Ink item to two parts making it possible to attach it to existing MouseArea instead of including one inside 
* Writing custom Button alternative to use it only in Snackbar. 

I think most of this ways (probably excluding of the last one) is definitely way far out of scope of the current pull request but I'm ready to discuss options :)

**Comment by ricardomv** [comment]
@cyberbobs yes i meant just top, bottom and right edges not the whole Snackbar.
For the Ink maybe we can remove the MouseArea and pass it as a property like we do with Scrollbars and add a flag to disable it.

**Comment by ricardomv** [comment]
Anyway patches LGTM :+1: buttons look a bit small to me but they conform with the spec so that may have to be fixed in the dp scaling.

**Comment by ricardomv** [comment]
Merged. Thanks

**Pull request closed without merging**
