### PR TITLE
Equal icon added

### PR DESCRIPTION
**Pull request by PierreJacquier**
To use with papyros-calculator

### CODE REVIEW

**Comment by iBeliever** [comment]
Thanks for the pull request! I moved the icon to a new "extra" icon group (so now it's `extra/equal`), since it's not a Google-provided icon.

**Comment by boghison** [comment]
Why do we need an icon for a text character?

**Comment by PierreJacquier** [comment]
I use it in the calculator app, with a FAB, because we can't insert text in it, can we ? 
(Off topic : The FAB is a bit useless, but I have no idea where to place the equal instead. However, suggestions are welcome !)

**Comment by boghison** [comment]
@PierreJacquier Maybe you could take inspiration from the Android Lollipop calculator

**Comment by PierreJacquier** [comment]
@boghison That's exactly whàt I was checking on my phone ah ah.

**Pull request closed without merging**
