### PR TITLE
[Snackbar] Fix typo in button width calculation

### PR DESCRIPTION
**Pull request by malwoden**

### CODE REVIEW

**Comment by VirusKA** [comment]
u got an issue here

**Comment by malwoden** [comment]
Is the CI setup wrong at the moment? The build is failing due to qmake failing in the qml-extras dir which makes sense as that project has been purged.

**Comment by ricardomv** [comment]
@malwoden yes i don't see an issue with your commit. I think pulling qml-extras broke the CI build

**Comment by malwoden** [comment]
Issued a PR for the build fail due to qml-extras at #262. Though the build with still fail due to #260

**Comment by iBeliever** [comment]
Thanks for the fix!

**Pull request closed without merging**
