### PR TITLE
Fixes some binding loops in SimpleMenu and MenuField

### PR DESCRIPTION
**Pull request by jneidlinger**
Fixes some binding loops in SimpleMenu and MenuField which can happen when their internal ListView is empty.

Fixes issue #125

### CODE REVIEW

**Comment by ricardomv** [comment]
Nice :+1: i'm not getting any warnings now. But you should use spaces for the indentation and the "Fixes issue XXX" needs to go in the commit message.

**Comment by jneidlinger** [comment]
Oops, sorry, have to switch the tab style between projects, I forgot.

**Comment by jneidlinger** [comment]
@ricardomv should be good now

**Comment by MaxMansfield** [comment]
@jneidlinger Thanks for the fix!

**Pull request closed without merging**
