### PR TITLE
Time picker #148

### PR DESCRIPTION
**Pull request by sdcoffey**
First stab at a Time Picker https://www.google.com/design/spec/components/pickers.html

### CODE REVIEW

**Comment by jneidlinger** [comment]
The Time Picker should be able to live outside of a dialog. Time picker should be a stand alone component, and we can include a specialized Dialog that contains a timer picker for that scenario. That would remove the need here to create a dialog base class.

**Comment by sdcoffey** [comment]
Cool, just pulled out the dialog base and the timepicker into it's own standalone item

**Comment by jneidlinger** [comment]
Demo:

timepickerdemo

**Comment by iBeliever** [comment]
Great work on this, thank you!

**Pull request closed without merging**
