### PR TITLE
Update TextField.qml with helper text, character counter, and error conditions following Material Design Spec

### PR DESCRIPTION
**Pull request by nathanhourt**
- Adds support for helper text (small text under the field, distinct
from the floating label/placeholder text)
 - Adds support for character counter and limit
 - Adds support for error conditions, which turn the helper text or
character counter and the underline red
 - Complies with Material Design Spec for vertical spacing on single-line text fields, particularly with helper texts, floating labels, and character counters

Potential issues:
 - Had to bump import QtQuick to 2.1, to get access to activeFocusOnTab property of Item. Without it, the fields did not fit properly into the focus chain
 - Had to change from QtQuick.Controls.TextField to a manually styled TextInput, as I could not figure out how to get the vertical spacing right in a TextFieldStyle. This means all properties of the TextInput are no longer exposed to users of this component unless they are aliased

Material Spec documents referenced:
http://www.google.com/design/spec/components/text-fields.html (see Single-line, Floating label and Character counter sections)
http://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors

### CODE REVIEW

**Comment by iBeliever** [comment]
Great work, thanks for the improvements!

**Comment by iBeliever** [comment]
It looks like there are conflicts in your pull request, would you mind merging in the latest changes from develop and fixing any conflicts?

**Comment by nathanhourt** [comment]
I've merged. I've also resolved the second issue I referenced above, where the properties of the underlying TextInput were not accessible. They are now accessible via the input property.

**Comment by iBeliever** [comment]
Thanks. This is awesome, great work! :+1:

**Pull request merged**
