### PR TITLE
button: add tint if flat button hovered or focussed

### PR DESCRIPTION
**Pull request by ricardomv**
http://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons

### CODE REVIEW

**Comment by ricardomv** [comment]
i wonder if we can use [Qt.lighter](http://doc-snapshot.qt-project.org/qt5-5.4/qml-qtqml-qt.html#lighter-method) to set the colors since in google specs it says 
```
Height: 36dp
Hover: 20% #999999
Pressed: 40% #999999
Disabled text: 26% #000000
```

**Comment by iBeliever** [comment]
@ricardomv You can just use `Theme.alpha("#999", 0.20)` to do that. Do you want to go ahead and update it to that?

**Comment by ricardomv** [comment]
We should probably update it everywhere so we don't lose consistency. I'm a bit busy right now, i had this change here since the holidays.

**Comment by iBeliever** [comment]
Ok, I can tackle the change. Want me to close this and do it myself?

**Comment by ricardomv** [comment]
Merge this first and then change it there are a lot of places it needs to be changed

**Comment by iBeliever** [comment]
Thanks for your work on this!

**Pull request merged**
