### PR TITLE
Fix packaging

### PR DESCRIPTION
**Pull request by geiseri**
Currently there are two build errors when creating a package.  One is stated in #406 but there is also an issue when you create the processed qmldir.  If the target directory is not present (as it is when the PKGBUILD runs) then it will fail.  This change allows it to post process the qmldir file and then install it to the proper location.

### CODE REVIEW

**Comment by geiseri** [comment]
This looks like a false failure.

**Comment by MaxMansfield** [comment]
+1

**Comment by geiseri** [comment]
Can someone look at this one?  Thanks!

**Comment by geiseri** [comment]
bump.

**Comment by geiseri** [comment]
It looks like the git clean calls are failing.  The unit tests and lint tests pass though from what i can tell.  Whats up with that?

**Comment by iBelieve** [comment]
Thanks for the pull request! :+1:

**Pull request closed without merging**
