### PR TITLE
[DatePicker] Add Material DatePicker and DatePicker Dialog

### PR DESCRIPTION
**Pull request by jneidlinger**
Implements a Material styled QtQuick Controls Calendar.

Based on new designs here:

http://www.google.com/design/spec/components/pickers.html

Screenshots:

screen shot 2015-06-02 at 1 16 52 am

screen shot 2015-06-02 at 1 17 10 am

### CODE REVIEW

**Comment by ricardomv** [comment]
We should have a way to change the component color without having to change the theme accent color. One solution would be to add a `color` property to the control (root component) and set Theme.accentColor as the default color like in the TextField. And i think the Calendar style should be moved to a separate file in `modules/QtQuick/Controls/Styles/Material/`
But it's looking good :+1:

**Comment by ricardomv** [comment]
One thing we could add in the dialog is scrolling to change the month.

**Comment by espsousa** [comment]
Hi, I'm really new at QML, but I'm developing an application using qml-material from the papyros team. I'm really enjoying it and the application it's getting amazing thanks to all of you. Maybe in the future, if I learn it correctly, I could be a collaborator too. My question for now is: when will this component be added to the develop branch? Yesterday they added the TimePicker, that's just amazing, but I'm really waiting for the DatePicker too... Sorry about my english.

**Comment by ricardomv** [comment]
Merged, Thanks

**Pull request closed without merging**
