### PR TITLE
Create new MenuField widget

### PR DESCRIPTION
**Pull request by nathanhourt**
A new menu field widget which implements a combo-box style menu.
This widget is intended to fit in-line with TextField widgets,
thus its internal structure and exposed properties are similar.

This component is intended to mimic the "NY" field shown here:
http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7MHBnQlFGeFRtYTQ/components_menus_usage5.png

### CODE REVIEW

**Comment by nathanhourt** [comment]
It's definitely not perfect, but it's a start. Hope you find it useful. :)

**Comment by jneidlinger** [comment]
Instead of being a completely separate component, can we maybe make this be an extended functionality of our text fields? That is how material design describes these kind of fields: "drop down text fields"

Something like
        TextField {
            model: ["Apple","Orange","Banana","Grapefruit","Kiwi","Lemon","Watermelon"]
        }

Would be enough to tell the text field do draw the drop down arrow and behave as a drop down text field.

**Comment by nathanhourt** [comment]
Yes, that's entirely possible, though I felt it was easier to maintain if the two were separate. Separating them feels less hacky.

And yeah, that dummy model is still in there. I can remove that if you like.

**Comment by iBeliever** [comment]
I'd rather not combine the TextField and MenuField components, as they serve two different purposes; one allows you to type and edit text, the other lets you pick from a predefined list of choices.

**Comment by iBeliever** [comment]
@nathanhourt Great work on the new component, thanks! Just for future reference though, we use 4 spaces for indentation, not 3, so it would be helpful if you can do that in any future pull requests you submit.

**Pull request closed without merging**
