### PR TITLE
Have Action extend QtQuick's Action object

### PR DESCRIPTION
**Pull request by geiseri**
This gives keyboard accelerators, and the ability to assign actions directly into Button objects.  I also updated the demo so that it will use an Action inside of the ActionButton on the ButtonDemo page.

This should also address #249, #241 and might give a way to address #200.

I did not update anything that uses the Actions yet.  I wanted to make sure this was in line with current thinking.

### CODE REVIEW

**Comment by iBeliever** [comment]
Looks like a good improvement! I'd be happy to merge this if you want to make any necessary updates to uses of Action in the current code.

**Comment by geiseri** [comment]
Yes, I will do this tonight.  I made it so it was backwards compatible, but I need to review if there are any changes in the demo program to show the new way.

**Comment by iBeliever** [comment]
Thanks @geiseri

**Comment by oKcerG** [comment]
I don't really get why the new Action is done like that.

Why adding a iconSource property ? there's already one (it's a url and not a string though)
Why adding a text alias property, instead of aliasing name to the existing text property of Quick Controls' Action ?
same question for summary & tooltip

**Pull request closed without merging**
